apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.name" . }}-secrets
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.global.jwtSecret | b64enc | quote }}
  anon-key: {{ .Values.global.anonKey | b64enc | quote }}
  service-role-key: {{ .Values.global.serviceRoleKey | b64enc | quote }}
  postgres-password: {{ .Values.global.postgresPassword | b64enc | quote }}
  dashboard-username: {{ .Values.global.dashboardUsername | b64enc | quote }}
  dashboard-password: {{ .Values.global.dashboardPassword | b64enc | quote }}
  secret-key-base: {{ .Values.global.secretKeyBase | b64enc | quote }}
  vault-enc-key: {{ .Values.global.vaultEncKey | b64enc | quote }}
  pg-meta-crypto-key: {{ .Values.global.pgMetaCryptoKey | b64enc | quote }}
  s3-protocol-access-key-id: {{ .Values.global.s3ProtocolAccessKeyId | b64enc | quote }}
  s3-protocol-access-key-secret: {{ .Values.global.s3ProtocolAccessKeySecret | b64enc | quote }}
