apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "supabase.name" . }}-storage-data
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.persistence.size }}
